sonar.projectKey=CarolineCesi_Collector_shop
sonar.organization=carolinecesi
sonar.host.url=https://sonarcloud.io

# Define the source code directories
sonar.sources=frontend/src,api_gateway/src,service_catalogue/src,service_utilisateur/src

# Exclude node_modules and tests from analysis
sonar.exclusions=**/node_modules/**, **/*.test.js, **/*.spec.js, frontend/dist/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# JavaScript specific configurations
sonar.javascript.environments=node,browser
sonar.javascript.lcov.reportPaths=coverage/lcov.info
