apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - db-catalogue.yaml
  - db-utilisateur.yaml
  - frontend.yaml
  - keycloak.yaml
  - secrets.yaml
  - service-catalogue.yaml
  - service-utilisateur.yaml

configMapGenerator:
  - name: catalogue-db-init
    files:
      - catalogue-init.sql
  - name: user-db-init
    files:
      - user-init.sql

generatorOptions:
  disableNameSuffixHash: true
