apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - frontend.yaml
  - service-catalogue.yaml
  - service-utilisateur.yaml
  - keycloak.yaml
  - postgres-catalogue.yaml
  - postgres-utilisateur.yaml