apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD_CATALOGUE: secret_catalogue
  POSTGRES_DB_CATALOGUE: catalogue_db
  POSTGRES_PASSWORD_USER: secret_user
  POSTGRES_DB_USER: user_db
  KC_DB_URL: jdbc:postgresql://db-utilisateur:5432/user_db
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
