apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

commonLabels:
  env: dev

images:
  - name: frontend
    newName: collector-frontend
    newTag: dev
  - name: service-catalogue
    newName: collector-catalogue
    newTag: dev
  - name: service-utilisateur
    newName: collector-utilisateur
    newTag: dev
  - name: api-gateway
    newName: collector-gateway
    newTag: dev
