apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-dev.yaml

patches:
  - path: patch-keycloak.yaml
  - path: patch-pull-policy.yaml
  - path: patch-api-gateway.yaml
  
namespace: dev

labels:
  - pairs:
      env: dev
    includeSelectors: true

images:
  - name: collector-frontend
    newName: ghcr.io/carolinecesi/collector-frontend
    newTag: dev
  - name: collector-catalogue
    newName: ghcr.io/carolinecesi/collector-catalogue
    newTag: dev
  - name: collector-utilisateur
    newName: ghcr.io/carolinecesi/collector-utilisateur
    newTag: dev
  - name: collector-gateway
    newName: ghcr.io/carolinecesi/collector-gateway
    newTag: dev
