apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-staging.yaml

namespace: staging

commonLabels:
  env: staging

images:
  - name: frontend
    newName: collector-frontend
    newTag: staging
  - name: service-catalogue
    newName: collector-catalogue
    newTag: staging
  - name: service-utilisateur
    newName: collector-utilisateur
    newTag: staging
  - name: api-gateway
    newName: collector-gateway
    newTag: staging

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: service-catalogue
    spec:
      replicas: 2
